version: "3.7"
services:
  db:
    image: mysql:8.0.19
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backnet
    environment:
      - MYSQL_DATABASE=example
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password
    ports:
      - 3306:3306
  backend:
    build: backend
    restart: on-failure
    secrets:
      - db-password
    ports:
      - 5000:5000
    networks:
      - backnet
    depends_on:
      - db 
  notebook:
    build: notebook
    restart: always
    ports:
      - 8585:8585
    networks:
      - backnet
    secrets:
      - db-password
volumes:
  db-data:
secrets:
  db-password:
    file: db/password.txt
networks:
  backnet:
